
  - description: null
    label: "Globals"
    name: "clippings"
    sort: 1
    listed: true
    hasRoute: false
    showAsTable: false
    parent: null
    content: "/content/clippings.yaml"
    fields:
      - name: "site_name"
        label: "Site Name"
        description: null
        datatype: "text"
        sort: 1
        required: true
        relationship: null
        settings:
          options: {}
      - name: "logo"
        label: "Site Logo"
        description: null
        datatype: "images"
        sort: 2
        required: null
        relationship: null
        settings:
          limit: 1
          options: {}
  - description: null
    label: "Homepage"
    name: "homepage"
    sort: 1
    listed: true
    hasRoute: true
    showAsTable: false
    parent: null
    view: "/views/homepage.tpl"
    content: "/content/homepage.yaml"
    fields:
      - name: "hero_title"
        label: "Hero Title"
        description: ""
        datatype: "text"
        sort: 0
        required: false
        relationship: null
        settings:
          defaultValue: null
          list: true
      - name: "hero_subtitle"
        label: "Hero Subtitle"
        description: ""
        datatype: "textarea"
        sort: 1
        required: false
        relationship: null
        settings:
          defaultValue: null
          list: true
      - name: "map_header_title"
        label: "Map Header Title"
        description: ""
        datatype: "text"
        sort: 2
        required: false
        relationship: null
        settings:
          defaultValue: null
          list: true
      - name: "map_header_subtitle"
        label: "Map Header Subtitle"
        description: ""
        datatype: "text"
        sort: 3
        required: false
        relationship: null
        settings:
          defaultValue: null
          list: true
      - name: "services_title"
        label: "Services Title"
        description: ""
        datatype: "text"
        sort: 4
        required: false
        relationship: null
        settings:
          defaultValue: null
          list: true
      - name: "stats_title"
        label: "Stats Title"
        description: ""
        datatype: "text"
        sort: 5
        required: false
        relationship: null
        settings:
          defaultValue: null
          list: true
      - name: "stories_title"
        label: "Stories title"
        description: ""
        datatype: "text"
        sort: 6
        required: false
        relationship: null
        settings:
          defaultValue: null
          list: true
      - name: "contact_title"
        label: "Contact Title"
        description: ""
        datatype: "text"
        sort: 7
        required: false
        relationship: null
        settings:
          defaultValue: null
          list: true
      - name: "contact_subtitle"
        label: "Contact Subtitle"
        description: ""
        datatype: "textarea"
        sort: 8
        required: false
        relationship: null
        settings:
          defaultValue: null
          list: true
  - description: ""
    label: "Program Template"
    name: "program_template"
    sort: 100
    listed: true
    hasRoute: true
    showAsTable: false
    parent: null
    view: "/views/program_template.tpl"
    content: "/content/program_template.yaml"
    fields: []
  - description: ""
    label: "Events Template"
    name: "events_template"
    sort: 104
    listed: true
    hasRoute: true
    showAsTable: false
    parent: null
    view: "/views/events_template.tpl"
    content: "/content/events_template.yaml"
    fields: []
  - description: ""
    label: "Volunteer Template"
    name: "volunteer_template"
    sort: 106
    listed: true
    hasRoute: true
    showAsTable: false
    parent: null
    view: "/views/volunteer_template.tpl"
    content: "/content/volunteer_template.yaml"
    fields: []
  - description: ""
    label: "Careers Template"
    name: "careers_template"
    sort: 108
    listed: true
    hasRoute: true
    showAsTable: false
    parent: null
    view: "/views/careers_template.tpl"
    content: "/content/careers_template.yaml"
    fields: []
  - description: ""
    label: "Ways to give Template"
    name: "ways_to_give_template"
    sort: 110
    listed: true
    hasRoute: true
    showAsTable: false
    parent: null
    view: "/views/ways_to_give_template.tpl"
    content: "/content/ways_to_give_template.yaml"
    fields: []
  - description: ""
    label: "Newsroom Template"
    name: "newsroom_template"
    sort: 112
    listed: true
    hasRoute: true
    showAsTable: false
    parent: null
    view: "/views/newsroom_template.tpl"
    content: "/content/newsroom_template.yaml"
    fields: []
  - description: ""
    label: "Program Templates"
    name: "program_templates"
    sort: 114
    listed: true
    hasRoute: true
    showAsTable: true
    parent: null
    view: "/views/program_templates.tpl"
    content: "/content/program_templates.yaml"
    fields:
      - name: "test_title"
        label: "test_title"
        description: ""
        datatype: "text"
        sort: 0
        required: false
        relationship: null
        settings:
          defaultValue: null
          list: true
      - name: "sort"
        label: "sort"
        description: ""
        datatype: "sort"
        sort: 1
        required: false
        relationship: null
        settings:
          defaultValue: null
          list: true
  - description: ""
    label: "About Templates"
    name: "about_templates"
    sort: 116
    listed: true
    hasRoute: true
    showAsTable: true
    parent: null
    view: "/views/about_templates.tpl"
    content: "/content/about_templates.yaml"
    fields:
      - name: "test_title"
        label: "test_title"
        description: ""
        datatype: "text"
        sort: 0
        required: false
        relationship: null
        settings:
          defaultValue: null
          list: true
      - name: "sort"
        label: "sort"
        description: ""
        datatype: "sort"
        sort: 1
        required: false
        relationship: null
        settings:
          defaultValue: null
          list: true
  - description: ""
    label: "Volunteer Templates"
    name: "volunteer_templates"
    sort: 117
    listed: true
    hasRoute: true
    showAsTable: true
    parent: null
    view: "/views/volunteer_templates.tpl"
    content: "/content/volunteer_templates.yaml"
    fields:
      - name: "test_title"
        label: "Test title"
        description: ""
        datatype: "text"
        sort: 0
        required: false
        relationship: null
        settings:
          defaultValue: null
          list: true
      - name: "sort"
        label: "sort"
        description: ""
        datatype: "sort"
        sort: 1
        required: false
        relationship: null
        settings:
          defaultValue: null
          list: true
  - description: ""
    label: "Events Templates"
    name: "events_templates"
    sort: 118
    listed: true
    hasRoute: true
    showAsTable: true
    parent: null
    view: "/views/events_templates.tpl"
    content: "/content/events_templates.yaml"
    fields:
      - name: "test_title"
        label: "Test Title"
        description: ""
        datatype: "text"
        sort: 0
        required: false
        relationship: null
        settings:
          defaultValue: null
          list: true
      - name: "sort"
        label: "sort"
        description: ""
        datatype: "sort"
        sort: 1
        required: false
        relationship: null
        settings:
          defaultValue: null
          list: true
  - description: ""
    label: "All Programs Templates"
    name: "all_programs_templates"
    sort: 119
    listed: true
    hasRoute: true
    showAsTable: true
    parent: null
    content: "/content/all_programs_templates.yaml"
    fields:
      - name: "test_title"
        label: "Test Title"
        description: ""
        datatype: "text"
        sort: 0
        required: false
        relationship: null
        settings:
          defaultValue: null
          list: true
      - name: "sort"
        label: "sort"
        description: ""
        datatype: "sort"
        sort: 1
        required: false
        relationship: null
        settings:
          defaultValue: null
          list: true
  - description: ""
    label: "Corppage"
    name: "corppage"
    sort: 128
    listed: true
    hasRoute: true
    showAsTable: false
    parent: null
    view: "/views/corppage.tpl"
    content: "/content/corppage.yaml"
    fields: []
  - description: ""
    label: "Newsroom Templates"
    name: "newsroom_templates"
    sort: 132
    listed: true
    hasRoute: true
    showAsTable: true
    parent: null
    view: "/views/newsroom_templates.tpl"
    content: "/content/newsroom_templates.yaml"
    fields:
      - name: "test_title"
        label: "test_title"
        description: ""
        datatype: "text"
        sort: 0
        required: false
        relationship: null
        settings:
          defaultValue: null
          list: true
      - name: "sort"
        label: "sort"
        description: ""
        datatype: "sort"
        sort: 1
        required: false
        relationship: null
        settings:
          defaultValue: null
          list: true
  - description: ""
    label: "National Stats"
    name: "national_stats"
    sort: 133
    listed: true
    hasRoute: false
    showAsTable: false
    parent: null
    content: "/content/national_stats.yaml"
    fields:
      - name: "title"
        label: "Title"
        description: ""
        datatype: "text"
        sort: 0
        required: false
        relationship: null
        settings:
          defaultValue: null
          list: true
      - name: "subtitle"
        label: "Subtitle"
        description: ""
        datatype: "text"
        sort: 1
        required: false
        relationship: null
        settings:
          defaultValue: null
          list: true
      - name: "image"
        label: "Image"
        description: ""
        datatype: "images"
        sort: 2
        required: false
        relationship: null
        settings:
          defaultValue: null
          limit: ""
          list: true
      - name: "test"
        label: "Test"
        description: ""
        datatype: "one_to_many"
        sort: 3
        required: false
        relationship:
          name: "clippings"
          display: "site_name"
        settings:
          defaultValue: null
          list: true
  - description: ""
    label: "Career Template"
    name: "career_template"
    sort: 137
    listed: true
    hasRoute: true
    showAsTable: false
    parent: null
    view: "/views/career_template.tpl"
    content: "/content/career_template.yaml"
    fields: []
  - description: ""
    label: "News Archive Templates"
    name: "news_archive_templates"
    sort: 142
    listed: true
    hasRoute: true
    showAsTable: true
    parent: null
    view: "/views/news_archive_templates.tpl"
    content: "/content/news_archive_templates.yaml"
    fields:
      - name: "test_title"
        label: "Test Title"
        description: ""
        datatype: "text"
        sort: 0
        required: false
        relationship: null
        settings:
          defaultValue: null
          list: true
      - name: "sort"
        label: "sort"
        description: ""
        datatype: "sort"
        sort: 1
        required: false
        relationship: null
        settings:
          defaultValue: null
          list: true
  - description: ""
    label: "Events Single Templates"
    name: "events_single_templates"
    sort: 145
    listed: true
    hasRoute: true
    showAsTable: true
    parent: null
    view: "/views/events_single_templates.tpl"
    content: "/content/events_single_templates.yaml"
    fields:
      - name: "test_title"
        label: "Test Title"
        description: ""
        datatype: "text"
        sort: 0
        required: false
        relationship: null
        settings:
          defaultValue: null
          list: true
      - name: "sort"
        label: "Sort"
        description: ""
        datatype: "sort"
        sort: 1
        required: false
        relationship: null
        settings:
          defaultValue: null
          list: true
  - description: ""
    label: "Corporate Partnership"
    name: "corporate_partnership"
    sort: 148
    listed: true
    hasRoute: true
    showAsTable: true
    parent: null
    view: "/views/corporate_partnership.tpl"
    content: "/content/corporate_partnership.yaml"
    fields:
      - name: "test_title"
        label: "Test Title"
        description: ""
        datatype: "text"
        sort: 0
        required: false
        relationship: null
        settings:
          defaultValue: null
          list: true
      - name: "sort"
        label: "sort"
        description: ""
        datatype: "sort"
        sort: 1
        required: false
        relationship: null
        settings:
          defaultValue: null
          list: true
  - description: ""
    label: "Test"
    name: "test"
    sort: 151
    listed: true
    hasRoute: true
    showAsTable: false
    parent: null
    view: "/views/test.tpl"
    content: "/content/test.yaml"
    fields:
      - name: "test_title"
        label: "Test title"
        description: ""
        datatype: "text"
        sort: 0
        required: false
        relationship: null
        settings:
          defaultValue: null
          list: true
